baseURL = "https://apisets.info/"
languageCode = "en-us"

title = "apisets index"
theme = "kraiklyn-multipage"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  sidebarColor = "default"
  externalTitle = "links"
  customCss = ["css/kraiklyn-override.css"]

[[menu.shortcuts]]
  name = "apisets on Github"
  url = "https://github.com/learn-more/apisets"
  weight = 10

[[menu.shortcuts]]
  name = "data files (json)"
  url = "https://github.com/learn-more/apisets/tree/master/data/apisetschema"
  weight = 11

