baseURL = "https://apisets.info/"
languageCode = "en-us"

title = "apisets index"
theme = "kraiklyn-multipage"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[Params]
  sidebarColor = "default"
  externalTitle = "links"

[[menu.shortcuts]]
  name = "apisets on Github"
  url = "https://github.com/learn-more/apisets"
  weight = 10

